name: liminal_launcher
description: "An Android launcher."
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Flutter (Google)
  go_router: ^18.0.0
  intl: ^0.20.2
  local_auth: ^3.0.1
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2

  # Community
  after_layout: ^1.2.0
  flutter_secure_storage: ^11.0.0
  font_awesome_flutter: ^11.0.0
  line_icons: ^2.0.3
  provider: ^6.1.5+1

  # YWT
  ywt_private:
    path: ../ywt_private
  open_ui:
    path: ../open_ui

dev_dependencies:
  dependency_validator: ^5.0.5
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/app-icon.png

flutter_launcher_icons:
  image_path: assets/app-icon.png
  adaptive_icon_foreground: assets/app-icon.png
  adaptive_icon_background: "#000000"
  android: true
  ios: false
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false