name: liminal_launcher
description: "An Empathetech Android launcher."
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Flutter (Google)
  go_router: ^14.8.1
  http: ^1.6.0
  intl: ^0.20.2
  local_auth: ^3.0.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

  # Community
  feedback: ^3.2.0
  flutter_localized_locales: ^2.0.5
  flutter_platform_widgets: ^9.0.0
  go_transitions: ^0.8.3
  provider: ^6.1.5+1
  shake: ^3.0.0

  efui_bios:
    path: ../efui_bios
  empathetech_flutter_ui:
    path: ../empathetech_flutter_ui

dev_dependencies:
  dependency_validator: ^5.0.3
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/app-icon.jpg      

flutter_launcher_icons:
  image_path: assets/images/app-icon.jpg
  adaptive_icon_foreground: assets/images/app-icon.jpg
  adaptive_icon_background: "#000000"
  android: true
  ios: false
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false